version: '3.8'

services:
  backend:
    build: ./backend
    container_name: task_manager_backend
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: task_manager_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
